logging_inputs:
  - name: remote_udp_input
    type: remote
    udp_ports: [ 514 ]
  - name: remote_tcp_input
    type: remote
    tcp_ports: [ 514 ]
logging_outputs:
  - name: remote_files_output
    type: remote_files
logging_flows:
  - name: flow_0
    inputs: [remote_udp_input, remote_tcp_input]
    outputs: [remote_files_output]
